import type { Metadata } from "next";
import { Geist, Geist_Mono, Sixtyfour } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const sixtyfourSans = Sixtyfour({
  variable: "--font-sixtyfour",
  subsets: ["latin"],
  weight: ["400"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sixtyfourSans.variable} antialiased`}
      >
        <p>Antes</p>
        {children}
        <p>Después</p>
      </body>
    </html>
  );
}
